event:
    path: /
    controller: App\Controller\EventController::index
events:
    path: /event/load
    controller: App\Controller\EventController::getEvents
    methods:    POST
get_event:
    path: /event/detail/{id}
    controller: App\Controller\EventController::getEvent
    methods: GET
event_create:
    path: /event/create
    controller: App\Controller\EventController::create
prices:
    path:       /table-prices
    controller: App\Controller\HomeController::prices
login:
    path:       /login
    controller: App\Controller\UserController::login
logout:
    path: /logout
register:
    path:       /register
    controller: App\Controller\UserController::register
edit_my_profile:
    path:       /my-profile/edit
    controller: App\Controller\UserController::edit
upload_cover_profile:
    path:       /my-profile/photo-new
    controller: App\Controller\UserController::editphoto
    methods:    POST

set_interest:
    path:   /event/plus/interest
    controller: App\Controller\EventController::SetInterestForEvent
    methods: POST

view_interest:
    path: /event/myinterest
    controller:  App\Controller\EventController::myinterests

get_interest:
    path: /event/myinterest/load
    controller: App\Controller\EventController::GetMyInterest
    methods: POST
set_assistant:
    path: /event/plus/assistant
    controller: App\Controller\EventController::SetAssistant
    methods: POST

whereiwillgo:
    path: /events/whereiwillgo
    controller: App\Controller\EventController::whereiwillgo

test:
    path: /event
    controller: App\Controller\EventController::test