twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        varGlobImgAvatars: 'images/users/avatars/'
        varGlobImgEvents: 'images/events/covers/'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'